# Generated by Django 5.0.6 on 2024-06-05 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 5, 9, 42, 37, 988011, tzinfo=datetime.timezone.utc)),
        ),
    ]
