# Generated by Django 5.0.6 on 2024-06-06 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 8, 31, 11, 493158, tzinfo=datetime.timezone.utc)),
        ),
    ]
